base_url = "https://laydros.github.io"
title = "Jason Hamilton"
description = "Personal website of Jason Hamilton"

compile_sass = true
minify_html = false
generate_feeds = true

taxonomies = [
  {name = "tags"},
  {name = "categories"},
]

[markdown]
highlight_code = true

[extra]

# Skip problematic external links that fail due to redirects, bot protection, etc.
[link_checker]
skip_prefixes = [
    "https://twitter.com/",
    "https://stackoverflow.com/",
    "https://www.fakepersongenerator.com/",
    "https://raddle.me",
    "https://libredd.it/",
    "https://linode.com/",
    "https://computableverse.com/",
    "https://drewdevault.com/",
    "https://blogspot.com/",
    "http://calummacrae.blogspot.com/",
    "https://support.lenovo.com/",
]