base_url = "https://laydros.github.io"
title = "Jason Hamilton"
description = "Personal website of Jason Hamilton"

compile_sass = true
minify_html = false
generate_feeds = true
generate_sitemap = true
build_search_index = true

taxonomies = [
  {name = "tags"},
  {name = "categories"},
]

[markdown]
highlight_code = true
highlight_theme = "monokai"

[extra]

# Link checking configuration - external checking disabled for speed/reliability
[link_checker]
external_level = "warn"  # Disable external link checking (set to "error" to re-enable)
# Skip list for problematic external links (for when external checking is enabled)
skip_prefixes = [
    "https://twitter.com/",
    "https://stackoverflow.com/",
    "https://www.fakepersongenerator.com/",
    "https://raddle.me",
    "https://libredd.it/",
    "https://linode.com/",
    "https://computableverse.com/",
    "https://drewdevault.com/",
    "https://blogspot.com/",
    "http://calummacrae.blogspot.com/",
    "https://support.lenovo.com/",
    "https://freedombox.org/",
    "https://www.leancrew.com/",
    "https://www.perplexity.ai/",
]
