name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check site
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          CHECK: true
      - name: Build with Zola
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_ONLY: true

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check site before deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          CHECK: true
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages